source 'https://rubygems.org'

gem 'slack-ruby-bot-server', path: '../../'
gem 'newrelic-slack-ruby-bot'
gem 'rack-server-pages'
gem 'pg'
gem 'activerecord'

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'fabrication'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'database_cleaner'
end
