source 'https://rubygems.org'

gem 'mongoid'
gem 'slack-ruby-bot-server', path: '../../'
gem 'newrelic-slack-ruby-bot'

gem 'kaminari-mongoid'
gem 'mongoid-scroll'

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'fabrication'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'database_cleaner'
  gem 'rack-test'
end
