AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 500
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml
