source 'https://rubygems.org'

gem 'slack-ruby-bot-server', path: '../'
gem 'newrelic-slack-ruby-bot'

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'rack-test'
  gem 'fabrication'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'database_cleaner'
end
