source 'https://rubygems.org'

gem 'slack_bot_server', github: 'dblock/slack-bot-server', branch: :master, require: false
gem 'newrelic-slack-ruby-bot'

group :test do
  gem 'rspec'
  gem 'fabrication'
  gem 'faker'
  gem 'vcr'
  gem 'webmock'
  gem 'database_cleaner'
end
